name: myapp
description: "MEBN APP DANIEL"

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  provider: ^6.1.2
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  google_nav_bar: ^5.0.6
  firebase_core: ^2.31.1
  universal_io: ^2.2.2
  intl: ^0.17.0
  shared_preferences: ^2.2.3
  localization: ^2.1.1
  carousel_slider: ^4.2.1
  getwidget: ^4.0.0
  country_picker: ^2.0.26

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/

